# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Kotlin CI with Gradle

on:
  push:
    branches: [ master_kotlin ]
  pull_request:
    branches: [ master_kotlin ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Execute Gradle task
      uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
    - name: Test with Gradle
      run: ./gradle test
