name: Scala CI

on:
  push:
    branches:
      - master
      - 'branches/**'
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests with coverage
      run: sbt coverage test
    - name: Generate Coverage Report
      run: sbt coverageReport
    - name: Send Coverage Report to Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
